system:
  project: PROJ
  exp_name: cardiac_mpl_mri2ct
  n_threads: 8
  ckpt_dir: 'DIR'
  seed: 0

train: 
  lr: 1e-4 
  batch_size: 1
  weight_decay: 0.01
  betas: (0.9, 0.999)
  niter: 0
  niter_decay: 150
  type: 'mpl'
  mask_ratio: 0.7
  cls_num: 5
  warmup: 50
  save_epoch_freq: 50
  patience: 75

data: 
  val_img: 'DIR'
  val_label: 'DIR'
  src_data: 'DIR'
  tgt_data: 'DIR'

model:
  pretrain_model: 'PTH'
  large_scale: False # note that we set large-scale to False for cardiac exps because it only involves dozens of scans 