system:
  project: PROJ
  exp_name: X_site_70_final_testtime
  n_threads: 8
  ckpt_dir: 'DIR'
  seed: 0

train: 
  lr: 1e-4 
  batch_size: 1
  weight_decay: 0.01
  betas: (0.9, 0.999)
  niter: 0
  niter_decay: 100
  type: 'mpl'
  mask_ratio: 0.7
  test_time: True
data: 
  val_img: 'DIR'
  val_label: 'DIR'
  src_data: 'DIR'
  tgt_data: 'DIR'

model:
  pretrain_model: 'PTH'
  large_scale: True